import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import * as THREE from "three";

import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";

import Stats from "three/examples/jsm/libs/stats.module";
import { Scene } from "three";
import SceneInit from "@/lib/ScenceInit";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    const launchScene = new SceneInit("myThreeJsCanvas");

    launchScene.initialize();

    launchScene.animate();

    const boxGeometry = new THREE.BoxGeometry(16, 16, 16);

    const boxMaterial = new THREE.MeshNormalMaterial();

    const boxMesh = new THREE.Mesh(boxGeometry, boxMaterial);

    launchScene.scene.add(boxMesh);



  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative">
        <div>
          <div className="bg-red-500 absolute top-40 left-40">How are u</div>
          <canvas id="myThreeJsCanvas"></canvas>
        </div>
      </main>
    </>
  );
}
